-- Products table schema for Zaxis Studio
-- Run this in Supabase SQL editor or your Postgres client

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  title text not null,
  price numeric not null default 0,
  image_url text,
  created_at timestamp with time zone default now()
);

create index if not exists products_title_idx on public.products (title);
